[package]
name = "hello_rust"
version = "0.1.0"
edition = "2021"
authors = ["Matias Korhonen <me@matiaskorhonen.fi>"]
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.4" }
